// <auto-generated />
using System;
using Lot.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lot.Repo.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180908161801_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Lot.Data.Models.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Cerrado");

                    b.Property<string>("Descripcion");

                    b.Property<DateTime>("Fechafin");

                    b.Property<DateTime>("Fechainicio");

                    b.Property<string>("Nombre");

                    b.Property<string>("TarjetaWin");

                    b.HasKey("Id");

                    b.ToTable("Evento");
                });

            modelBuilder.Entity("Lot.Data.Models.Tarjeta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EventoId");

                    b.Property<int>("Numero");

                    b.Property<bool>("Reservada");

                    b.HasKey("Id");

                    b.HasIndex("EventoId");

                    b.ToTable("Tarjeta");
                });

            modelBuilder.Entity("Lot.Data.Models.Tarjeta", b =>
                {
                    b.HasOne("Lot.Data.Models.Evento", "Evento")
                        .WithMany("Tarjeta")
                        .HasForeignKey("EventoId");
                });
#pragma warning restore 612, 618
        }
    }
}
